runtime: nodejs20
instance_class: F1

handlers:
  # Tangani semua route frontend
  - url: /.*/
    static_files: build/index.html
    upload: build/index.html

  # Tangani semua file statis React (JS, CSS, dll)
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
    secure: always
    redirect_http_response_code: 301

env_variables:
  NODE_ENV: production
