runtime: nodejs20
instance_class: F1

handlers:
  # Menangani semua permintaan dan arahkan ke index.html
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html

  # Menangani semua file statis di folder build
  - url: /static
    static_dir: build/static

env_variables:
  NODE_ENV: production
